disabled_rules:
  - redundant_optional_initialization
  - statement_position
  - void_return

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - extension_access_modifier
  - file_header # ???
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded: 
  - Tests

warning_threshold: 1

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  VirgilCryptoAPI
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} VirgilSecurity\. All rights reserved\.
                    \/\/