language: objective-c
osx_image: xcode10.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilCryptoAPI.xcodeproj
    - IOS_SDK=iphonesimulator12.2
    - MACOS_SDK=macosx10.14
    - TVOS_SDK=appletvsimulator12.2
    - WATCHOS_SDK=watchsimulator5.2
    - FRAMEWORK_NAME=VirgilCryptoAPI
    - REPO=VirgilSecurity/virgil-cryptoapi-x

  matrix:
    - DESTINATION=""                                         PREFIX=""         SDK=""              BUILD="0"  PUBLISH_CARTHAGE="YES"      PUBLISH_POD="YES" POD_LIB_LINT="YES"  PUBLISH_DOCS="YES"  SWIFT_LINT="YES"
    - DESTINATION="OS=12.2,name=iPhone SE"                   PREFIX="iOS"      SDK="$IOS_SDK"      BUILD="2"  PUBLISH_CARTHAGE="NO"       PUBLISH_POD="NO"  POD_LIB_LINT="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="arch=x86_64"                              PREFIX="macOS"    SDK="$MACOS_SDK"    BUILD="2"  PUBLISH_CARTHAGE="NO"       PUBLISH_POD="NO"  POD_LIB_LINT="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="OS=12.2,name=Apple TV 4K"                 PREFIX="tvOS"     SDK="$TVOS_SDK"     BUILD="2"  PUBLISH_CARTHAGE="NO"       PUBLISH_POD="NO"  POD_LIB_LINT="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="OS=5.2,name=Apple Watch Series 4 - 44mm"  PREFIX="watchOS"  SDK="$WATCHOS_SDK"  BUILD="1"  PUBLISH_CARTHAGE="NO"       PUBLISH_POD="NO"  POD_LIB_LINT="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"


before_install:
  - set -e
  - set -o pipefail

script:
  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi

  - SCHEME="VirgilCryptoAPI ${PREFIX}"

  - |
    if [ $BUILD == "2" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
      # Run Tests
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
    elif [ $BUILD == "1" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
    fi

  # Check pod lib
  - if [ $POD_LIB_LINT == "YES" ]; then
      gem install cocoapods --pre;
      pod repo update;
      pod lib lint;
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      brew update && brew upgrade carthage || true;
      carthage build --no-skip-current;
      carthage archive;
    fi

  # Generate and publish docs
  - if [[ $PUBLISH_DOCS = "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      ./CI/publish-docs.sh;
    fi

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: $FRAMEWORK_NAME.framework.zip
    skip_cleanup: true
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"

  # Publish pod
  - provider: script
    script: bash CI/publish-cocoapods.sh
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_POD == "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+

  # Upload docs to gh-pages
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: "docs"
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_DOCS = "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+
